project_name: memcached-cli
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: memcached-cli
    ldflags:
      - -s -w
      - -X github.com/lupinthe14th/memcached-cli/pkg/version.Version={{.Version}}
      - -X github.com/lupinthe14th/memcached-cli/pkg/version.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
